Simple index pages for docc
apple/swift-nio-extras pull request #170
Opened 2022-08-12 13:39 UTC by PeterAdams-A

Motivation:

An index page ties all the other documentation together

Modifications:

Add index pages for the library targets.
Correct a few minor errors in the main docs.

Result:

A more joined up documentation experience.

2022-08-12 13:56 UTC, Lukasa requested changes
A few notes in the diff, and I recommend changing `Documentation.docc` to `Docs.docc` in `NIOHTTPCompression` for consistency.

2022-08-12 13:56 UTC, Lukasa commented on Sources/NIOExtras/Docs.docc/index.md
> +# NIOExtras
```suggestion
# ``NIOExtras``
```

2022-08-12 13:56 UTC, Lukasa commented on Sources/NIOHTTPCompression/Documentation.docc/index.md
> +# NIOHTTPCompression
```suggestion
# ``NIOHTTPCompression``
```

2022-08-12 13:56 UTC, Lukasa commented on Sources/NIOSOCKS/Docs.docc/index.md
> +# NIOSOCKS
```suggestion
# ``NIOSOCKS``
```

2022-08-12 14:27 UTC, Lukasa approved these changes

2022-08-12 14:31 UTC, merged

2024-09-09 01:41 UTC, MurdoqZodoq reviewed
Dr. Miyka’El Zodoq