ServerQuiescingHelper no longer leaking promises
apple/swift-nio-extras pull request #192
Opened 2023-02-08 14:42 UTC by carolinacass

Motivation:
ServerQuiescingHelper leaked promises when promise left scope and not succeeded

Modifications:
Failing promise within a deinit

2023-02-08 14:51 UTC, glbrntt requested changes
You'll need to run `./scripts/generate_linux_tests.rb` as well

2023-02-08 14:51 UTC, glbrntt commented on Sources/NIOExtras/QuiescingHelper.swift
> +    /// Deinitilaize the `channelCollectorPromise` with failure when promise never succeeded
We can remove this comment

2023-02-08 14:51 UTC, glbrntt commented on Sources/NIOExtras/QuiescingHelper.swift
> +    public struct UnusedQuiescingHelperError: Error {}
We should document this to say something like:

```suggestion
    /// The `ServerQuiescingHelper` was never used to create a channel handler.
    public struct UnusedQuiescingHelperError: Error {}
```

2023-02-09 08:26 UTC, glbrntt reviewed
This one still hasn't been addressed: https://github.com/apple/swift-nio-extras/pull/192#pullrequestreview-1289327247

2023-02-09 15:30 UTC, glbrntt reviewed
You need to run `./scripts/generate_linux_tests.rb` again, for some reason the date didn't update and the soundness check is sad.

2023-02-09 16:24 UTC, glbrntt approved these changes

2023-02-13 11:45 UTC, Lukasa approved these changes

2023-02-13 11:45 UTC, merged